### ISSUE TITLE
KB.Rmd deleted

### ISSUE THREAD

**Issue by vasishth** [dmbates/RePsychLing#2]
Has the inst/doc/KB.Rmd file been deleted? Why?

**Comment by dmbates** [comment]
According to what I understand of the "acceptable" procedures for R package vignettes, the source file is supposed to be in the `vignettes` directory and the process of building the vignettes is what transfers those files to the `inst/doc` directory.

I suppose we could just omit the `vignettes` directory and keep everything in `inst/doc` but doing so will likely violate several dozen CRAN rules.  As we will never be submitting this package to CRAN, I guess that isn't a problem.  It would be convenient whatever we choose to do doesn't mess things up when using `devtools::install_github`.

In any case we don't want to have copies of the source files in two different directories, as that is just asking for trouble.

**Comment by vasishth** [comment]
I have moved my Rmd files (Stan models) to vignettes.
