### ISSUE TITLE
Stan model object is large! 

### ISSUE THREAD

**Issue by vasishth** [dmbates/RePsychLing#3]
The model object is 300MB or so and residing in data. I could load it via a URL link from my own server, if it's going to be a problem. Let me know, I will remove it if it is.

**Comment by dmbates** [comment]
What is it used for?

**Comment by vasishth** [comment]
Good point; I will only save the summary results. Will just delete it.

## 

Shravan Vasishth
Professor for Psycholinguistics and Neurolinguistics
Department of Linguistics
University of Potsdam, Germany
http://www.ling.uni-potsdam.de/~vasishth

**Comment by dmbates** [comment]
Can you close the issue after deleting the file, please?
