### ISSUE TITLE
[Resolved] Fail to find or run rePCA()

### ISSUE THREAD

**Issue by wychow** [dmbates/RePsychLing#9]
Update: This problem went away once i have updated all my packages in R. Sorry!
# 

I followed the given instructions to install RePsychLing, which went smoothly:
devtools::install_github("dmbates/RePsychLing") 

However, once i've loaded the library, i keep getting this error when i try to run rePCA() on a lmer model:

> m0 <- lmer(value ~ sentencetype \* congruity + (sentencetype \* congruity|subj) + (sentencetype \* congruity|item), REML=FALSE, data=tempdata)
> rePCA(m0)
> Error in match.arg(name) : 
>   'arg' should be one of “X”, “Z”, “Zt”, “Ztlist”, “mmList”, “y”, “mu”, “u”, “b”, “Gp”, “Tp”, “L”, “Lambda”, “Lambdat”, “Lind”, “A”, “RX”, “RZX”, “sigma”, “flist”, “fixef”, “beta”, “theta”, “ST”, “REML”, “is_REML”, “n_rtrms”, “n_rfacs”, “N”, “n”, “p”, “q”, “cnms”, “devcomp”, “offset”, “lower”

I actually couldn't find a rePCA.R file in my R's library\RePsychLing\ directory , and when i tried installing RePsychLing again I realised it says:

Downloading GitHub repo dmbates/RePsychLing@master from URL https://api.github.com/repos/dmbates/RePsychLing/zipball/master

Does it mean I didn't get the right RePsychLing in my R library? What should i do? Many thanks!

Wing-Yee Chow

**Comment by vasishth** [comment]
Resolved by wychow herself.
